<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?= $this->view->getTitle();?></title>
        <meta name="description" content="<?= $this->view->getDescription();?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/main.css">
        <script src="http://localhost:35729/livereload.js"></script>
    </head>
    <body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    
    <header>   			
        <div class="container">
            <div class="presentation-ht floatleft">
                <h1>Eric Gianna</h1>
            </div>
            <nav class="floatright">
                <ul id="nav">
                    <li <?= $this->view->isLinkActive('home')?>><a href="/home" >accueil</a></li>
                    <li <?= $this->view->isLinkActive('portfolio')?>><a href="/portfolio" >portfolio</a></li>
                    <li <?= $this->view->isLinkActive('contact')?>><a href="/contact" >contact</a></li>
					<li <?= $this->view->isLinkActive('cv')?>><a href="/cv">Télécharger le cv</a></li>
					
                </ul>
            </nav>
            <div class="clear"></div>
        </div>
        <div class="fdmarr float">
        <div class="container">	
<marquee direction="left" bgcolor="#42432d" width="100%"><font color="white">Infographiste / Développeur web</font></marquee>
        </div><!-- /.container -->
        </div>
    </header>

    <div class="container" id="fd_body">
        <?= $this->content ?>    
    </div>

    <footer>
        <div class="container">
            <ul class="foot">
                <li class="padd">99, avenue Barthélémy Buyer - 69005 LYON</li>   						
                <li class="floatleft"><a href="/contact" title="eric.gianna@free.fr"><img alt="mail" src="../img/mail.png">eric.gianna@free.fr</a></li>
                <li class="floatleft"><img alt="phone" src="../img/phone.png">06 84 53 87 02</li>
                <li class="floatleft"><a href="http://www.viadeo.com/fr/profile/eric.gianna"><img alt="viadeo" src="../img/viadeo.png">Viadeo</a></li>
                <li>
            </ul>
        </div><!-- /.container -->
    </footer>	
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/assets/jquery/dist/jquery.min.js"><\/script>');</script>
    </body>
</html>
