<?php 
$this->setTitle('CV');
$this->setDescription('CV de Eric Gianna');
?>

<table class="fdcv">
	<tr>
		<td>
			<iframe src="/img/cv_Eric_Gianna.pdf" width="817" height="1128"></iframe>
		</td>
	</tr>
</table>
<!--

<table class="fdcv">
	<tr>
		<td>
			<object width="808" height="1133" type="application/pdf" data="cv_Eric_Gianna.pdf" name="PDF" id="PDF">
			<param name="src" value="/img/cv_Eric_Gianna.pdf" />
			</object>
		</td>
	</tr>
</table>
-->
