<?php 
$this->setTitle('Accueil');
$this->setDescription('accueil de Eric Gianna');
?>
	<div>
		<div class="presentation floatleft">
			<img id="photo" src="/img/moicadre.jpg" alt="ma photo"/>
			<p class="gras">Plus de 15 ans <br>d’expérience <br>dans le pré-presse : </p>
			<div><p class="retrait"><span class="puce"></span> Gestion<br>contraintes techniques<br>en amont et en aval<br>de la réalisation<br>(conseil clients, correction fichiers transmis aux imprimeurs ou façonniers),<br></p>
			</div>
			<div><p class="retrait"><span class="puce"></span> Maîtrise<br>la chaîne graphique<br> </p></div>
			<div><p class="retrait"><span class="puce"></span> Contact direct<br>avec les clients<br></p></div>
			<div><p class="retrait"><span class="puce"></span> Gestion dossiers de<br>la demande à la remise<br>des travaux finis<br></p></div>
			<p class="gras">N'hésitez pas ! <br>Contactez-moi pour toute information ou projet !</p>
		</div>
		<details open>
		   <summary>Compétences Infographiques et Techniques</summary>
		   <table>
		      <tr>
		         <th class="th_larg">Print</th>
		         <th>Web</th>		         
		      </tr>
		      <tr>
				<td>
			      	<ul>
			         	<li><span class="puce"></span> Affiches</li>
			        	<li><span class="puce"></span> Flyers / Dépliants</li>
			        	<li><span class="puce"></span> Plaquettes</li>
			        	<li><span class="puce"></span> Catalogues</li>
			        	<li><span class="puce"></span> Annonces presse</li>
			        	<li><span class="puce"></span> Logotypes</li>
			        	<li><span class="puce"></span> Journaux…</li>
					</ul>
		        </td>
		         <td>
					<ul>
						<li><span class="puce"></span> Html5 / Css3</li>
						<li><span class="puce"></span> Php5 / MySql</li>
						<li><span class="puce"></span> Javascript / Jquery</li>
						<li><span class="puce"></span> CMS : Wordpress</li>
					</ul>
		         </td>
		      </tr>
		   </table>
		</details>
		<details>
		   <summary>Applications</summary>
		   <table>
		      <tr>
		         <th class="th_larg">Print</th>
		         <th>Web</th>
		      </tr>
		      <tr>
				<td>
			      	<ul>
			         	<li><meter value="85" max="100">85%</meter> Quark X-Press</li>
			        	<li><meter value="80" max="100">80%</meter> Illustrator</li>
			        	<li><meter value="90" max="100">90%</meter> Photoshop</li>
			        	<li><meter value="90" max="100">90%</meter> InDesign</li>
			        	<li><meter value="85" max="100">85%</meter> Acrobat</li>
			        	<li>...</li>
					</ul>
		        </td>
		         <td>
			         <ul>
			         	<li><meter value="75" max="100">75%</meter> Dreamweaver</li>
			         	<li><meter value="75" max="100">75%</meter> IDE (Aptana, <br>Netbeans, Zend Studio)</li>
			         	<li><meter value="75" max="100">50%</meter> 
			        	<li>...</li>
			        </ul>
		         </td>
				<tr>
		         <th class="th_larg">Bureautique</th>
		         <th>Outils web</th>
		         </tr>
				<tr>
		         <td>
			         <ul>
			         	<li><meter value="75" max="100">75%</meter> Word</li>
			         	<li><meter value="60" max="100">60%</meter> Excel</li>
			         	<li><meter value="50" max="100">50%</meter> Powerpoint</li>
			         	<li>...</li>
			         </ul>
				</td>
				<td>
			         <ul>
			         	<li><span class="puce"></span> Puphpet / Vagrant</li>
						<li><span class="puce"></span> Grunt / Bower</li>
						<li><span class="puce"></span> Less / Bootstrap</li>
						<li><span class="puce"></span> Github</li>
						<li>...</li>	
			         </ul>
		         </td>	         
		       </tr>
		   </table>
		</details>
		<details>
		<summary>Expériences</summary>
		   <table>
			<tr><th>A.P.O. (Atelier Photogravure Offset) :</th></tr>
			<tr>
				<td>
					<ul>
						<li class="vert">(avril 1998  •&rsaquo;  février 2014)</li>
			         	<li class="retrait"><span class="puce"></span> Traitement de l’image (chromie, retouche, photomontage, détourage)</li>
			         	<li class="retrait"><span class="puce"></span> Mise en page, création, exécution, langues étrangères (grec, cyrillique…) pour la publicité et l’édition</li>
			         	<li class="retrait"><span class="puce"></span> Quelques clients : Euro RSCG, Aldes, Avon, Calor, Celda, Continents du Monde, Essilor, Group Aoste, IARP, Laforêt Immobilier, Publiprint, Renault Trucks, Rostaing, Sonepar, Tigex, Théâtre des Céléstins, Volvo Trucks…)</li> 
					</ul>
		        </td>
		 	</tr>
		 	<tr><th>Info Régie :</th></tr>
			<tr>
				<td>
					<ul>
						<li class="vert">(janvier 1993  •&rsaquo; avril 1998)</li>
			         	<li>Conception, réalisation de publicités et mise en page de :
			         	<li class="retrait"><span class="puce"></span> Cahiers régionaux (Rhône, Loire, Ain, Jura, Côte d’Or) de l’hebdomadaire TV Magazine.</li>
			         	<li class="retrait"><span class="puce"></span> 10 journaux hebdomadaires gratuits de petites annonces : RSO (Le Local).</li> 
			         	<li class="retrait"><span class="puce"></span> Mensuels gratuits l’Echo d’Oullins et l’Espace Immobilier.</li> 
			         	<li class="retrait"><span class="puce"></span> Suppléments au quotidien régional Le Progrès.</li> 
					</ul>
		        </td>
		 	</tr>
		 	<tr>
				<th>Comareg :</th>
			</tr>
			<tr>
				<td>
					<ul>
						<li class="vert">(avril 1992  •&rsaquo; janvier 1993</li>
			         	<li class="retrait"><span class="puce"></span> Conception, réalisation et mise en page des publicités pour 13 journaux gratuits (Le 38 Vienne, Le 42 St-Etienne, Le 69 Affaires et Immo, Le 71 Chalon…).</li> 
			         	</ul>
		        </td>
		 	</tr>
		 </table>
	</details>
	</div>
						<div class="clear"></div>


<!-- 
Expériences 
• > A.P.O. (Atelier Photogravure Offset) : 
(avril 1998  • >  février 2014) 
Traitement de l’image (chromie, retouche, photomontage, détourage), mise en page, création, exécution, langues étrangères (grec, cyrillique…) pour la publicité et l’édition (Euro RSCG, Aldes, Avon, Calor, Celda, Continents du Monde, Essilor, Group Aoste, IARP, Laforêt Immobilier, Publiprint, Renault Trucks, Rostaing, Sonepar, Tigex, Théâtre des Céléstins, Volvo Trucks…). 

• > Info Régie : 
(janvier 1993  • > avril 1998) 
Conception, réalisation de publicités et mise en page de : - Cahiers régionaux (Rhône, Loire, Ain, Jura, Côte d’Or) de l’hebdomadaire TV Magazine.
- 10 journaux hebdomadaires gratuits de petites annonces : RSO (Le Local).
- Mensuels gratuits l’Echo d’Oullins et l’Espace Immobilier.
- Suppléments au quotidien régional Le Progrès.

• > Comareg :
(avril 1992  • > janvier 1993)
Conception, réalisation et mise en page des publicités pour 13 journaux gratuits (Le 38 Vienne, Le 42 St-Etienne, Le 69 Affaires et Immo, Le 71 Chalon…).


Diplômes
• > E.S.C.O.M. :
Ecole Supérieure de Communication de Lyon (1991).
• > Baccalauréat G3 :
techniques commerciales, marketing, communication (1988).
Divers
• > Délégué de parents d’élèves.
• > Passion pour le jeu d’échecs, l’escalade et le badminton.


Compétences Infographiques et Techniques
• > Print : Affiches / flyers / plaquettes / catalogues / dépliants /  annonces presse / logotypes / journaux…
• > Web : Html / css / flash.
• > Maîtrise des logiciels :  X-Press, Illustrator, Photoshop, Acrobat, InDesign…
• > Connaissance des logiciels Dreamweaver, Flash, Word, Excel, PowerPoint…
• > Maîtrise du macintosh et de son environnement (utilisation et maintenance), bonne connaissance de l’environnement pc et du web…
• > Formations aux logiciels  Flash 8 (techniques d’animation, d’interactivité et action-script) et Director 4.0.
• > Gestion de clientèle : contact direct avec les clients, conseil, gestion des dossiers de la demande à la remise des travaux finis.
• > Maîtrise de la chaîne graphique : plus de 15 ans d’expérience dans le pré-presse, gestion des contraintes techniques en amont et en aval de la réalisation des travaux (conseil aux clients, correction de problèmes liés aux fichiers transmis aux imprimeurs ou façonniers).
-->

