<?php 
$this->setTitle('Accueil');
$this->setDescription('accueil de Eric Gianna');
?>
	<div>
		<div class="presentation floatleft">
			<img id="photo" src="/img/moicadre.jpg" alt="ma photo"/>
			<p class="gras">Plus de 15 ans <br>d’expérience <br>dans le pré-presse : </p>
			<div><p class="retrait"><span class="puce"></span> Gestion<br>contraintes techniques<br>en amont et en aval<br>de la réalisation<br>(conseil clients, correction fichiers transmis aux imprimeurs ou façonniers),<br></p>
			</div>
			<div><p class="retrait"><span class="puce"></span> Maîtrise<br>la chaîne graphique<br> </p></div>
			<div><p class="retrait"><span class="puce"></span> Contact direct<br>avec les clients<br></p></div>
			<div><p class="retrait"><span class="puce"></span> Gestion dossiers de<br>la demande à la remise<br>des travaux finis<br></p></div>
			<p class="gras">N'hésitez pas ! <br>Contactez-moi pour toute information ou projet !</p>
		</div>
		
		<div class="floatright accordion horizontal">
		<h2 class="interligne">Compétences <br>Infographiques et Techniques</h2>
		  <section id="print">
		      <h2><a href="#print">Print</a></h2>
				<table>
					<tr>
						<td>
					      	<ul>
					         	<li><span class="puce"></span> Affiches</li>
					        	<li><span class="puce"></span> Flyers</li>
					        	<li><span class="puce"></span> Dépliants</li>
					        	<li><span class="puce"></span> Plaquettes</li>
					        	<li><span class="puce"></span> Catalogues</li>
							</ul>
						</td>
						<td>
					        <ul>
					        	<li><span class="puce"></span> Annonces presse</li>
					        	<li><span class="puce"></span> Logotypes</li>
					        	<li><span class="puce"></span> Journaux</li>
					        	<li><span class="puce"></span> ...</li>
					        </ul>
					    </td>
				</table>
		  </section>					
		  <section id="web">
		      <h2><a href="#web">Web</a></h2>				
					<ul>
						<li><span class="puce"></span> Html5 / Css3</li>
						<li><span class="puce"></span> Php5 / MySql</li>
						<li><span class="puce"></span> Javascript / Jquery</li>
						<li><span class="puce"></span> CMS : Wordpress</li>
			        	<li><span class="puce"></span> ...</li>
					</ul>
		  </section>
		  <section id="os">
		      <h2><a href="#os">O.S.</a></h2>				
			         <ul>
			         	<li>Maîtrise de système d'exploitation et environnement (utilisation et maintenance)</li>
			         	<li><meter value="90" max="100">90%</meter> Macintosh</li>
			         	<li><meter value="75" max="100">75%</meter> Windows</li>
			         	<li><meter value="50" max="100">50%</meter> Linux </li>
			        	<li>...</li>
			        </ul>
		  </section>
<div class="clear interligne"></div>
		  
		<h2 class="interligne">Applications</h2>
		  <section id="print2">
		      <h2><a href="#print2">Print</a></h2>
			      	<ul>
			         	<li><meter value="85" max="100">85%</meter> Quark X-Press</li>
			        	<li><meter value="80" max="100">80%</meter> Illustrator</li>
			        	<li><meter value="90" max="100">90%</meter> Photoshop</li>
			        	<li><meter value="90" max="100">90%</meter> InDesign</li>
			        	<li><meter value="85" max="100">85%</meter> Acrobat</li>
			        	<li>...</li>
					</ul>
		  </section>
		  <section id="web2">
		      <h2><a href="#web2">Web</a></h2>
			      	<ul>
			         	<li><meter value="75" max="100">75%</meter> Dreamweaver</li>
			         	<li><meter value="75" max="100">75%</meter> IDE (Aptana, Netbeans, Zend Studio)</li>
			         	<li><meter value="75" max="100">50%</meter> Flash </li>
			        	<li>...</li>
			        </ul>
		  </section>
		  <section id="outilsweb">
		      <h2><a href="#outilsweb">Outils web</a></h2>
			      	<ul>
			         	<li><span class="puce"></span> Puphpet / Vagrant</li>
						<li><span class="puce"></span> Grunt / Bower</li>
						<li><span class="puce"></span> Less / Bootstrap</li>
						<li><span class="puce"></span> Github</li>
						<li><span class="puce"></span> ...</li>	
			        </ul>
		  </section>
		  <section id="bureautique">
		      <h2><a href="#bureautique">Bureautique</a></h2>
			      	<ul>		        
						<li><meter value="75" max="100">75%</meter> Word</li>
			         	<li><meter value="60" max="100">60%</meter> Excel</li>
			         	<li><meter value="50" max="100">50%</meter> Powerpoint</li>
			         	<li>...</li>
			         </ul>
		  </section>									
<div class="clear interligne"></div>
		  
		<h2 class="interligne">Expériences</h2>
		  <section id="fredel">
		      <h2><a href="#fredel">Fredel Agency</a></h2>
					<ul>
			         	<li class="retrait"><span class="puce"></span> 5 semaines de stage.</li>
			         	<li class="retrait"><span class="puce"></span> Corrections HTML et CSS sur un site de motivation des ventes.</li>
			         	<li class="retrait"><span class="puce"></span> "Refonte et relooking", découpage et intégration HTML/CSS, modifications PHP et base de donées du CRM (système de gestion de la relation client) interne de l'agence.</li>
						<li class="retrait vert right">(juin 2014 et juillet 2014)</li>
			         	</ul>
		  </section>
		  <section id="cared">
		      <h2><a href="#cared">IP Formation</a></h2>
			      	<ul>
			         	<li>Formation CARED (Contrat d'aide au Retour à un Emploi Durable) Développeur web </li>
						<li class="retrait"><span class="puce"></span> Création et intégration HTML5 et CSS3</li>
			         	<li class="retrait"><span class="puce"></span> Programmation procédurale, orientée objet et algorithmique (PHP, Javascript, Jquery)</li>
			         	<li class="retrait"><span class="puce"></span> Systèmes de Gestion de Bases de Données</li>
			         	<li class="retrait"><span class="puce"></span> serveur virtualisé (Debian), IDE, versionning...</li>
			        	<li class="retrait"><span class="puce"></span> ...</li>
						<li class="retrait right vert">(avril 2014  •&rsaquo;  août 2014)</li>

			        </ul>
		  </section>
		  <section id="apo">
		      <h2><a href="#apo">A.P.O. (Atelier Photogravure Offset)</a></h2>
			      	<ul>
			         	<li class="retrait"><span class="puce"></span> Traitement de l’image (chromie, retouche, photomontage, détourage)</li>
			         	<li class="retrait"><span class="puce"></span> Mise en page, création, exécution, langues étrangères (grec, cyrillique…) pour la publicité et l’édition</li>
			         	<li class="retrait"><span class="puce"></span> Quelques clients : Euro RSCG, Aldes, Avon, Calor, Celda, Continents du Monde, Essilor, Group Aoste, IARP, Laforêt Immobilier, Publiprint, Renault Trucks, Rostaing, Sonepar, Tigex, Théâtre des Céléstins, Volvo Trucks…)</li> 
						<li class="right vert">(avril 1998  •&rsaquo;  février 2014)</li>
			         	</ul>
		  </section>
		  <section id="ir">
		      <h2><a href="#ir">Info Régie<br> Groupe Progrès</a></h2>
			      	<ul>		        
						<li class="retrait">Conception, réalisation de publicités et mise en page de :
			         	<li class="retrait"><span class="puce"></span> Cahiers régionaux (Rhône, Loire, Ain, Jura, Côte d’Or) de l’hebdomadaire TV Magazine.</li>
			         	<li class="retrait"><span class="puce"></span> 10 journaux hebdomadaires gratuits de petites annonces : RSO (Le Local).</li> 
			         	<li class="retrait"><span class="puce"></span> Mensuels gratuits l’Echo d’Oullins et l’Espace Immobilier.</li> 
			         	<li class="retrait"><span class="puce"></span> Suppléments au quotidien régional Le Progrès.</li> 
						<li class="right vert">(janvier 1993  •&rsaquo; avril 1998)</li>
			         	</ul>
		  </section>
		  <section id="comareg">
		      <h2><a href="#comareg">Comareg</a></h2>
			      	<ul>		        
			         	<li class="retrait"><span class="puce"></span> Conception, réalisation et mise en page des publicités pour 13 journaux gratuits :<br>Le 38 Vienne, Le 42 St-Etienne, Le 69 Affaires et Immo, Le 71 Chalon…</li> 
						<li class="right vert">(avril 1992  •&rsaquo; janvier 1993</li>
			         </ul>
		  </section>
		<div class="clear"></div>
		  
		</div>		
		
		
<!-- 
			<details>
		<summary>Diplômes</summary>
		   <table>
			<tr><th>E.S.C.O.M. :</th></tr>
			<tr>
				<td>
					<ul>
			         	<li class="retrait"><span class="puce"></span> Ecole Supérieure de Communication de Lyon (1991).</li>
			         	<li class="retrait"><span class="puce"></span> Communication - Marketing - Relations public</li> 
					</ul>
		        </td>
		 	</tr>
		 	<tr><th>Baccalauréat G3 :</th></tr>
			<tr>
				<td>
					<ul>
			         	<li class="retrait"><span class="puce"></span> techniques commerciales, marketing, communication (1988)..</li>
					</ul>
		        </td>
		 	</tr>
		 </table>
	</details>
			<details>
		<summary>Divers</summary>
		   <table>
			<tr>
				<td>
					<ul>
			         	<li class="retrait"><span class="puce"></span> Délégué de parents d’élèves.</li>
			         	<li class="retrait"><span class="puce"></span> Passion pour le jeu d’échecs</li>
						<li class="retrait"><span class="puce"></span> Pratique de l'escalade et du badminton en club</li> 
 
					</ul>
		        </td>
		 	</tr>
		 	<tr><th>Baccalauréat G3 :</th></tr>
			<tr>
				<td>
					<ul>
			         	<li class="retrait"><span class="puce"></span> techniques commerciales, marketing, communication (1988)..</li>
					</ul>
		        </td>
		 	</tr>
		 </table>
	</details>  -->
	</div>
<div class="clear"></div>


